[package]
name = "bmail"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
chrono = "0.4"
enum-kinds = "0.5"

[[bin]]
name = "header_layout"
path = "src/headers/layout.rs"
